on:
  push:
    branches:
      - 'main'
    paths:
      - 'pop-blob-cronjob/**'

jobs:
  build:
    name: Build and Push Docker Image for pop-blob-cronjob
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWD }}

      - name: Build and push Docker image
        run: |
            IMAGE_NAME="leeegiit/pop-blob-cronjob"
            echo "Building and pushing image for pop-blob-cronjob"
            docker build -t $IMAGE_NAME -f Dockerfile.pop .
            docker push $IMAGE_NAME