on:
  push:
    branches:
      - 'main'
    paths:
      - 'runner-migrations-blob/**'

jobs:
  build:
    name: Build and Push Docker Image for runner-migrations-blob
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWD }}

      - name: Build and push Docker image
        run: |
            IMAGE_NAME="leeegiit/runner-migrations-blob"
            echo "Building and pushing image for runner-migrations-blob"
            docker build -t $IMAGE_NAME -f Dockerfile.runner .
            docker push $IMAGE_NAME
